### ISSUE TITLE
change libgit2 to release version to resolve windows crash

### ISSUE THREAD

**Issue by kkHAIKE** [atom/git-utils#59]
https://github.com/atom/atom/issues/9339

**Comment by peol** [comment]
@50Wliu I'd say this is pretty critical (not really an enhancement imo), atom release 1.1.0 is unusable on Windows 10 at the moment :( Also due to how atom is built, you cannot easily stay on 1.0.x since it'll automatically update. I'm going to try building atom from source tomorrow to see if bumping `libgit2` fixes it (I'm relying my opinion on @kkHAIKE verifying that it has fixed the issue for him).

**Comment by pablobb** [comment]
I must agree with @peol. I have moved to beta because of electron error on windows, now this bug forces me to move back from beta and also 1.1 to old 1.0.19.
1.1 and beta 1.2 works with small repo, but when I'm trying to open a bigger one Atom crashes even on stable 1.1
